In [20]:
import numpy as np
import pandas as pd

In [21]:
df = pd.read_csv('X_train.txt', sep=' ', header=None)
display(df)
x_train = np.array(df.values)
print (x_train.shape)
print (x_train)

df = pd.read_csv('y_train.txt', sep=' ', header=None)
display(df)
y_train = df.values
print (y_train.shape)
print (y_train)

df = pd.read_csv('X_test.txt', sep=' ', header=None)
display(df)
x_test = df.values
print (x_test.shape)
print (x_test)

df = pd.read_csv('y_test.txt', sep=' ', header=None)
display(df)
y_test = df.values
print (y_test.shape)
print (y_test)

,0,1,2,3,4,5,6,7,8,9,...,551,552,553,554,555,556,557,558,559,560
0,0.043580,-0.005970,-0.035054,-0.995381,-0.988366,-0.937382,-0.995007,-0.988816,-0.953325,-0.794796,...,-0.012236,-0.314848,-0.713308,-0.112754,0.030400,-0.464761,-0.018446,-0.841559,0.179913,-0.051718
1,0.039480,-0.002131,-0.029067,-0.998348,-0.982945,-0.971273,-0.998702,-0.983315,-0.974000,-0.802537,...,0.202804,-0.603199,-0.860677,0.053477,-0.007435,-0.732626,0.703511,-0.845092,0.180261,-0.047436
2,0.039978,-0.005153,-0.022651,-0.995482,-0.977314,-0.984760,-0.996415,-0.975835,-0.985973,-0.798477,...,0.440079,-0.404427,-0.761847,-0.118559,0.177899,0.100699,0.808529,-0.849230,0.180610,-0.042271
3,0.039785,-0.011809,-0.028916,-0.996194,-0.988569,-0.993256,-0.996994,-0.988526,-0.993135,-0.798477,...,0.430891,-0.138373,-0.491604,-0.036788,-0.012892,0.640011,-0.485366,-0.848947,0.181907,-0.040826
4,0.038758,-0.002289,-0.023863,-0.998241,-0.986774,-0.993115,-0.998216,-0.986479,-0.993825,-0.801982,...,0.137735,-0.366214,-0.702490,0.123320,0.122542,0.693578,-0.615971,-0.848164,0.185124,-0.037080
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7762,0.048048,-0.042445,-0.065884,-0.195448,-0.278326,-0.219954,-0.282233,-0.305861,-0.357803,0.267874,...,-0.008381,-0.596760,-0.879026,-0.190437,0.829718,0.206972,-0.425619,-0.792292,0.238580,0.056020
7763,0.037639,0.006430,-0.044345,-0.235372,-0.302680,-0.232843,-0.322483,-0.354464,-0.345592,0.181271,...,0.209452,-0.404418,-0.684496,0.064907,0.875679,-0.879033,0.400219,-0.772288,0.252653,0.056252
7764,0.037451,-0.002724,0.021009,-0.218281,-0.378082,-0.076950,-0.304446,-0.400661,-0.193071,0.113141,...,0.237003,0.000207,-0.317314,0.052806,-0.266724,0.864404,0.701169,-0.779566,0.249121,0.047071
7765,0.044011,-0.004536,-0.051242,-0.219202,-0.383350,-0.081035,-0.310419,-0.380233,-0.201007,0.166671,...,0.069366,0.037919,-0.356579,-0.101360,0.700740,0.936674,-0.589479,-0.785603,0.246409,0.031700
7766,0.068954,0.001810,-0.080323,-0.269336,-0.366553,-0.147294,-0.377332,-0.360597,-0.255505,0.321881,...,0.002496,-0.400831,-0.742972,-0.280088,-0.007739,-0.056088,-0.616956,-0.783693,0.246785,0.042981

(7767, 561)
[[ 0.04357967 -0.00597022 -0.03505434 ... -0.84155851  0.17991281
  -0.05171842]
 [ 0.03948004 -0.00213128 -0.02906736 ... -0.8450924   0.18026111
  -0.04743634]
 [ 0.03997778 -0.00515272 -0.02265071 ... -0.84923013  0.18060956
  -0.04227136]
 ...
 [ 0.03745094 -0.00272442  0.02100941 ... -0.77956634  0.24912145
   0.04707077]
 [ 0.04401105 -0.00453578 -0.0512422  ... -0.78560327  0.24640867
   0.03170003]
 [ 0.06895376  0.00181032 -0.08032343 ... -0.78369253  0.24678499
   0.04298129]]

      0
0     5
1     5
2     5
3     5
4     5
...  ..
7762  2
7763  2
7764  2
7765  2
7766  2

[7767 rows x 1 columns]

(7767, 1)
[[5]
 [5]
 [5]
 ...
 [2]
 [2]
 [2]]

,0,1,2,3,4,5,6,7,8,9,...,551,552,553,554,555,556,557,558,559,560
0,0.030914,-0.008927,0.040382,-0.938504,-0.944626,-0.759334,-0.952398,-0.950281,-0.802483,-0.757099,...,0.122830,-0.345684,-0.709087,0.006462,0.162920,-0.825886,0.271151,-0.720559,0.276779,-0.051074
1,0.042548,0.001079,-0.026236,-0.975516,-0.977502,-0.960146,-0.986694,-0.978983,-0.966820,-0.757099,...,-0.314688,-0.142804,-0.600867,-0.083495,0.017500,-0.434375,0.920593,-0.698684,0.281322,-0.076825
2,0.038297,-0.011660,-0.025643,-0.993922,-0.979215,-0.973030,-0.994298,-0.980535,-0.977508,-0.799005,...,0.114730,-0.209525,-0.645500,-0.034956,0.202302,0.064103,0.145068,-0.703355,0.280062,-0.072302
3,0.036205,-0.018148,-0.025240,-0.994845,-0.981534,-0.976175,-0.995169,-0.983020,-0.980785,-0.798401,...,0.164515,-0.359352,-0.738474,-0.017067,0.154438,0.340134,0.296407,-0.699545,0.284093,-0.070079
4,0.038034,-0.013437,-0.032899,-0.993955,-0.977493,-0.984290,-0.994006,-0.977354,-0.985899,-0.798401,...,-0.056085,-0.544467,-0.846150,-0.002223,-0.040046,0.736715,-0.118545,-0.692849,0.290701,-0.066849
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3157,0.052279,-0.038687,-0.013494,-0.287933,-0.403601,-0.431550,-0.356012,-0.433826,-0.534817,0.244280,...,0.125445,-0.390349,-0.752788,-0.337422,0.346295,0.884904,-0.698885,-0.652416,0.274605,0.190104
3158,0.073745,-0.024673,-0.017836,-0.305455,-0.286487,-0.417996,-0.373468,-0.354849,-0.557925,0.244280,...,0.150787,-0.336001,-0.703532,-0.736701,-0.372889,-0.657421,0.322548,-0.655858,0.273556,0.187748
3159,0.068334,0.043822,-0.024135,-0.329706,-0.335273,-0.456965,-0.387944,-0.423504,-0.604403,0.079255,...,-0.004765,-0.139894,-0.476335,-0.181560,0.088574,0.696664,0.363139,-0.656034,0.274457,0.186527
3160,0.023016,0.032345,-0.011830,-0.323182,-0.465502,-0.426108,-0.392307,-0.520848,-0.569571,0.079255,...,0.013540,-0.224141,-0.623083,0.444558,-0.819188,0.929294,-0.008398,-0.660387,0.264759,0.192865
3161,-0.010846,-0.004134,-0.037678,-0.330114,-0.441542,-0.394796,-0.430898,-0.480065,-0.533532,-0.031137,...,0.046926,-0.094539,-0.446862,0.598808,-0.287951,0.876030,-0.024965,-0.660748,0.263914,0.193402

(3162, 561)
[[ 0.0309139  -0.00892689  0.04038223 ... -0.7205591   0.27677941
  -0.05107403]
 [ 0.04254816  0.00107859 -0.02623642 ... -0.6986837   0.28132158
  -0.07682459]
 [ 0.0382968  -0.01166028 -0.0256426  ... -0.70335515  0.28006162
  -0.07230248]
 ...
 [ 0.06833377  0.04382217 -0.02413471 ... -0.65603364  0.27445701
   0.18652707]
 [ 0.02301605  0.03234511 -0.01182959 ... -0.66038682  0.26475922
   0.1928648 ]
 [-0.0108462  -0.00413392 -0.03767837 ... -0.66074775  0.26391374
   0.19340177]]

      0
0     5
1     5
2     5
3     5
4     5
...  ..
3157  2
3158  2
3159  2
3160  2
3161  2

[3162 rows x 1 columns]

(3162, 1)
[[5]
 [5]
 [5]
 ...
 [2]
 [2]
 [2]]

In [22]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
x_train = ss.fit_transform(x_train)
x_test = ss.fit_transform(x_test)

In [23]:
print (x_train.shape)
print (x_train)

(7767, 561)
[[ 0.04726903 -0.05325364 -0.18793746 ... -0.69833245  0.43079362
   0.00423381]
 [ 0.00707236 -0.01485157 -0.12135729 ... -0.70527191  0.43195135
   0.0197386 ]
 [ 0.01195271 -0.0450759  -0.04999882 ... -0.71339714  0.43310957
   0.03844022]
 ...
 [-0.01282282 -0.020785    0.43553762 ... -0.57659902  0.66083999
   0.36193521]
 [ 0.0514986  -0.03890452 -0.36795979 ... -0.58845369  0.65182283
   0.30627997]
 [ 0.29606029  0.02457737 -0.69136698 ... -0.5847016   0.65307369
   0.34712779]]

In [24]:
print (x_test.shape)
print (x_test)

(3162, 561)
[[-0.09469648 -0.07064914  0.71331073 ... -0.4132924   0.64099005
  -0.02277109]
 [ 0.01987847  0.02709161 -0.08087122 ... -0.37007326  0.65492025
  -0.13024002]
 [-0.02198919 -0.0973509  -0.07379209 ... -0.37930262  0.65105613
  -0.11136717]
 ...
 [ 0.27381683  0.44464172 -0.05581606 ... -0.28580973  0.63386754
   0.96884758]
 [-0.17247507  0.33252549  0.09087723 ... -0.29441029  0.60412576
   0.99529785]
 [-0.50595271 -0.02382796 -0.21727425 ... -0.29512339  0.6015328
   0.99753885]]

In [25]:
y_train = y_train.squeeze()
y_test = y_test.squeeze()

### KNN

In [26]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
knn = KNeighborsClassifier()
hyper_param = {'n_neighbors':[3, 4, 5, 6, 7]}
knn_gs = GridSearchCV(knn, hyper_param, scoring='accuracy', cv=5).fit(x_train, y_train)

In [27]:
from sklearn.model_selection import cross_val_score
knn.n_neighbors = knn_gs.best_params_['n_neighbors']
knn_scores = cross_val_score(knn, x_test, y_test, cv=10)

In [28]:
print (knn_gs.best_params_)
print (np.mean(knn_scores))

{'n_neighbors': 7}
0.870969931717446

### Logistic Regression

In [29]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
lr = LogisticRegression(solver='lbfgs', max_iter=10000)
lr.fit(x_train, y_train)
lr_scores = cross_val_score(lr, x_test, y_test, cv=10, scoring='accuracy')

In [30]:
print (np.mean(lr_scores))

0.9237661222696962

### Naive Bayes

In [31]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import cross_val_score
nb = GaussianNB()
nb.fit(x_train, y_train)
nb_scores = cross_val_score(nb, x_test, y_test, cv=10, scoring='accuracy')

In [32]:
print (np.mean(nb_scores))
print (nb.score(x_test, y_test))

0.7159875014974244
0.717583807716635

### Decision Tree

In [33]:
from sklearn import tree
dt = tree.DecisionTreeClassifier()
dt = dt.fit(x_train, y_train)
dt_scores = cross_val_score(dt,x_test,y_test,cv=10,scoring='accuracy')

In [34]:
print (np.mean(dt_scores))

0.8213412929760813

### SVM

In [35]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
lsvm = SVC()
hyper_param = {'C':np.linspace(1e-5, 1e2, 10)}
lsvm_gs = GridSearchCV(lsvm, hyper_param, scoring='accuracy', cv=5).fit(x_train, y_train)

In [36]:
from sklearn.model_selection import cross_val_score
lsvm.C = lsvm_gs.best_params_['C']
svm_scores = cross_val_score(lsvm, x_test, y_test, cv=10)

In [37]:
print (lsvm.C)
print (np.mean(svm_scores))

22.22223
0.935151539352314

### MLP

In [38]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(random_state=0, max_iter=10000).fit(x_train, y_train)
print (mlp.score(x_test, y_test))

0.9399114484503479